"""empty message

Revision ID: 16e30d77f875
Revises: d98f4347b44c
Create Date: 2018-01-29 01:48:11.853596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e30d77f875'
down_revision = 'd98f4347b44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'author', sa.Column('email', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'email')
    # ### end Alembic commands ###
